name: line_icons_demo
description: A demo for the LineIcons library
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  line_icons: ^2.0.2
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter